# Python Script for Showing tweets from JSON file in Tabluar Form

In [8]:
import numpy as np                                                    #for storing data in array
import pandas as pd                                                   #for creating dataframe of tweets
import json                                                           #for common json functionalities

Function for opening json file

In [9]:
def json_input(location):
    with open(location) as json_file:  
        data = json.load(json_file)
        return data

In [10]:
data = json_input("tweets.json")

Converting Json data to DataFrame

In [11]:
tweets = pd.DataFrame.from_dict(data)

In [12]:
(tweets)

,Tweets,created_at,len,likes,retweets
0,RT @Harvard: Professor Jelani Nelson founded A...,1554786267000,136,0,33
1,RT @emnlp2019: For anyone interested in submit...,1554786251000,140,0,12
2,RT @multimediaeval: Announcing the 2019 MediaE...,1554752289000,140,0,15
3,"Many Congratulations to @midasIIITD student, S...",1554707292000,140,13,2
4,@midasIIITD thanks all students who have appea...,1554694062000,140,5,0
5,"@himanchalchandr Meanwhile, complete CV/NLP ta...",1554646649000,55,0,0
6,@sayangdipto123 Submit as per the guideline ag...,1554646629000,50,0,0
7,We request all students whose interview are sc...,1554637404000,140,1,1
8,"Other queries: ""none of the Tweeter Apis give ...",1554620119000,139,5,2
9,"Other queries: ""do we have to make two differe...",1554620018000,140,4,1
10,"Other queries: ""If using Twitter api, it does ...",1554615147000,140,6,1
11,Response to some queries asked by students on ...,1554614980000,140,7,1
12,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,1554570689000,89,0,2
13,@nupur_baghel @PennDATS Congratulation @nupur_...,1554569007000,140,18,3
14,We have emailed the task details to all candid...,1554480517000,140,11,1
15,RT @rfpvjr: Our NAACL paper on polarization in...,1554437111000,139,0,16
16,RT @kdnuggets: Effective Transfer Learning For...,1554437083000,98,0,11
17,RT @stanfordnlp: Whatâ€™s new in @Stanford CS224...,1554316313000,140,0,59
18,RT @DeepMindAI: Today we're releasing a large-...,1554311072000,140,0,870
19,RT @ylecun: Congratulations Jitendra Malik !\n...,1554282220000,113,0,16
20,RT @IIITDelhi: Another chance to take admissio...,1554277562000,140,0,4
21,Dear @midasIIITD internship candidates who hav...,1554178813000,140,8,1
22,Looking forward to your paper submission to @I...,1554173094000,140,5,1
23,RT @ngrams: Reproducibility in multimedia rese...,1554172544000,140,0,7
24,Online application for https://t.co/DJFDrQsHZP...,1554101588000,140,7,2
25,RT @ACMMM19: A final reminder of the Reproduci...,1554027684000,140,0,10
26,RT @isarth23: Thanks for the support and help ...,1553888604000,140,0,2
27,"Since SemEval-2019 will be held June 6-7, 2019...",1553879800000,140,9,1
28,+@aggarwal_kartik.\nCongrats! Wish you many mo...,1553879070000,56,2,0
29,RT @aggarwal_kartik: Our work (@midasIIITD ) a...,1553879009000,139,0,1
...,...,...,...,...,...
311,RT @TensorFlow: TensorFlow 1.10.0 has been rel...,1533794397000,140,0,265
312,@midasIIITD is looking for motivated IIITD MTe...,1533727856000,140,2,1
313,@IIITDelhi @ponguru @RatnRajiv The results of ...,1533707628000,96,3,1
314,RT @IIITDelhi: @midasIIITD has secured rank 1 ...,1533707158000,140,0,1
315,RT @kdnuggets: Comparison of Top 6 Python NLP ...,1533626193000,103,0,40
316,Check more details of the 20th IEEE Internatio...,1533607512000,118,1,1
317,MR2AMC@ISM 2018 will be organized by @RatnRaji...,1533607129000,135,1,1
318,"Our workshop proposal named, ""MR2AMC: Multimod...",1533606633000,140,1,1
319,@NUSComputing Congratulations Abdelhak and Pro...,1533577703000,59,0,0
320,RT @goodfellow_ian: One of the most anticipate...,1533577619000,123,0,103
321,@the_dhumketu Great to have you in @midasIIITD,1533535607000,46,0,0
322,Congratulation @soujanyaporia for being appoin...,1533275793000,140,6,1
323,@IIITDelhi @the_dhumketu Thanks team @midasIII...,1533124035000,72,5,1
324,RT @IIITDelhi: Congratulations @midasIIITD int...,1533122407000,140,0,4
325,RT @learning_pt: Profile of the 5 Indian under...,1533100007000,140,0,4
326,Have a look at the list of accepted papers in ...,1533039112000,140,1,0
327,RT @goodfellow_ian: https://t.co/hYiWI7ntyk Te...,1533002786000,139,0,264
328,RT @IIITDelhi: Congratulations Dr. @RatnRajiv ...,1532935851000,140,0,2
329,"RT @ylecun: Jitendra Malik, who directs FAIR-M...",1532776031000,140,0,57
330,RT @kdnuggets: .@Bloomberg launches free cours...,1532758449000,140,0,105
331,RT @TechAtBloomberg: Missed #PyLondinium18? Wa...,1532758428000,124,0,7
332,RT @IIITDelhi: We are delighted to announce th...,1532750901000,140,0,6
333,Get ready for the annual technical fest of @II...,1532674004000,140,3,2
334,Congratulations Dr. @RatnRajiv and team @midas...,1532664451000,139,8,2
335,Congratulations MIDAS @midasIIITD intern Prakh...,1532495675000,140,5,1
336,MIDAS@IIITD foundation. https://t.co/LKuzyBHzjm,1532428403000,47,2,1
337,It feels great to be the part of @IIITDelhi. h...,1532427154000,68,2,1
338,"Thank you, @toonzratn for designing the logo o...",1532425586000,78,4,1
339,We are on Facebook too. Like our page to get o...,1532363105000,121,3,1
340,MIDAS is a group of researchers at IIIT-Delhi ...,1532350395000,140,7,4